
export enum ActionTypes  {
  
  LOGIN = "LOGIN",
  
  "SET_INACTIVE_STATUS" = "SET_INACTIVE_STATUS",
  
  "SET_ACTIVE_STATUS" = "SET_ACTIVE_STATUS",
  "SET_INVISIBLE" = "SET_INVISIBLE",
  "SET_VISIBLE" = "SET_VISIBLE",
  "SET_OWN_VISIBILITY" = "SET_OWN_VISIBILITY"
}